/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivitesRouteImport } from './routes/activites'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as EnfantsRouteImport } from './routes/enfants'
import { Route as FacturationRouteImport } from './routes/facturation'
import { Route as FamillesRouteImport } from './routes/familles'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as InscriptionsRouteImport } from './routes/inscriptions'
import { Route as PaiementsRouteImport } from './routes/paiements'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as PersonnelRouteImport } from './routes/personnel'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as PresencesRouteImport } from './routes/presences'
import { Route as RapportsRouteImport } from './routes/rapports'
import { Route as RepasHygieneRouteImport } from './routes/repas-hygiene'
import { Route as SauvegardeRouteImport } from './routes/sauvegarde'
import { Route as TransmissionsRouteImport } from './routes/transmissions'
import { Route as UtilisateursRouteImport } from './routes/utilisateurs'
import { Route as EnfantsIdRouteImport } from './routes/enfants.$id'
import { Route as FamillesIndexRouteImport } from './routes/familles.index'
import { Route as FamillesIdRouteImport } from './routes/familles.$id'
import { Route as PersonnelEmployeeIdRouteImport } from './routes/personnel.$employeeId'
import { Route as TransmissionsIndexRouteImport } from './routes/transmissions.index'
import { Route as TransmissionsChildIdRouteImport } from './routes/transmissions.$childId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitesRoute = ActivitesRouteImport.update({
  id: '/activites',
  path: '/activites',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const EnfantsRoute = EnfantsRouteImport.update({
  id: '/enfants',
  path: '/enfants',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturationRoute = FacturationRouteImport.update({
  id: '/facturation',
  path: '/facturation',
  getParentRoute: () => rootRouteImport,
} as any)
const FamillesRoute = FamillesRouteImport.update({
  id: '/familles',
  path: '/familles',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionsRoute = InscriptionsRouteImport.update({
  id: '/inscriptions',
  path: '/inscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementsRoute = PaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonnelRoute = PersonnelRouteImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const PresencesRoute = PresencesRouteImport.update({
  id: '/presences',
  path: '/presences',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportsRoute = RapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const RepasHygieneRoute = RepasHygieneRouteImport.update({
  id: '/repas-hygiene',
  path: '/repas-hygiene',
  getParentRoute: () => rootRouteImport,
} as any)
const SauvegardeRoute = SauvegardeRouteImport.update({
  id: '/sauvegarde',
  path: '/sauvegarde',
  getParentRoute: () => rootRouteImport,
} as any)
const TransmissionsRoute = TransmissionsRouteImport.update({
  id: '/transmissions',
  path: '/transmissions',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilisateursRoute = UtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const EnfantsIdRoute = EnfantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EnfantsRoute,
} as any)
const FamillesIndexRoute = FamillesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FamillesRoute,
} as any)
const FamillesIdRoute = FamillesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FamillesRoute,
} as any)
const PersonnelEmployeeIdRoute = PersonnelEmployeeIdRouteImport.update({
  id: '/$employeeId',
  path: '/$employeeId',
  getParentRoute: () => PersonnelRoute,
} as any)
const TransmissionsIndexRoute = TransmissionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TransmissionsRoute,
} as any)
const TransmissionsChildIdRoute = TransmissionsChildIdRouteImport.update({
  id: '/$childId',
  path: '/$childId',
  getParentRoute: () => TransmissionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activites': typeof ActivitesRoute
  '/audit': typeof AuditRoute
  '/connexion': typeof ConnexionRoute
  '/documents': typeof DocumentsRoute
  '/enfants': typeof EnfantsRouteWithChildren
  '/facturation': typeof FacturationRoute
  '/familles': typeof FamillesRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/inscription': typeof InscriptionRoute
  '/inscriptions': typeof InscriptionsRoute
  '/paiements': typeof PaiementsRoute
  '/parametres': typeof ParametresRoute
  '/personnel': typeof PersonnelRouteWithChildren
  '/planning': typeof PlanningRoute
  '/presences': typeof PresencesRoute
  '/rapports': typeof RapportsRoute
  '/repas-hygiene': typeof RepasHygieneRoute
  '/sauvegarde': typeof SauvegardeRoute
  '/transmissions': typeof TransmissionsRouteWithChildren
  '/utilisateurs': typeof UtilisateursRoute
  '/enfants/$id': typeof EnfantsIdRoute
  '/familles/$id': typeof FamillesIdRoute
  '/personnel/$employeeId': typeof PersonnelEmployeeIdRoute
  '/transmissions/$childId': typeof TransmissionsChildIdRoute
  '/familles/': typeof FamillesIndexRoute
  '/transmissions/': typeof TransmissionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activites': typeof ActivitesRoute
  '/audit': typeof AuditRoute
  '/connexion': typeof ConnexionRoute
  '/documents': typeof DocumentsRoute
  '/enfants': typeof EnfantsRouteWithChildren
  '/facturation': typeof FacturationRoute
  '/forbidden': typeof ForbiddenRoute
  '/inscription': typeof InscriptionRoute
  '/inscriptions': typeof InscriptionsRoute
  '/paiements': typeof PaiementsRoute
  '/parametres': typeof ParametresRoute
  '/personnel': typeof PersonnelRouteWithChildren
  '/planning': typeof PlanningRoute
  '/presences': typeof PresencesRoute
  '/rapports': typeof RapportsRoute
  '/repas-hygiene': typeof RepasHygieneRoute
  '/sauvegarde': typeof SauvegardeRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/enfants/$id': typeof EnfantsIdRoute
  '/familles/$id': typeof FamillesIdRoute
  '/personnel/$employeeId': typeof PersonnelEmployeeIdRoute
  '/transmissions/$childId': typeof TransmissionsChildIdRoute
  '/familles': typeof FamillesIndexRoute
  '/transmissions': typeof TransmissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activites': typeof ActivitesRoute
  '/audit': typeof AuditRoute
  '/connexion': typeof ConnexionRoute
  '/documents': typeof DocumentsRoute
  '/enfants': typeof EnfantsRouteWithChildren
  '/facturation': typeof FacturationRoute
  '/familles': typeof FamillesRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/inscription': typeof InscriptionRoute
  '/inscriptions': typeof InscriptionsRoute
  '/paiements': typeof PaiementsRoute
  '/parametres': typeof ParametresRoute
  '/personnel': typeof PersonnelRouteWithChildren
  '/planning': typeof PlanningRoute
  '/presences': typeof PresencesRoute
  '/rapports': typeof RapportsRoute
  '/repas-hygiene': typeof RepasHygieneRoute
  '/sauvegarde': typeof SauvegardeRoute
  '/transmissions': typeof TransmissionsRouteWithChildren
  '/utilisateurs': typeof UtilisateursRoute
  '/enfants/$id': typeof EnfantsIdRoute
  '/familles/$id': typeof FamillesIdRoute
  '/personnel/$employeeId': typeof PersonnelEmployeeIdRoute
  '/transmissions/$childId': typeof TransmissionsChildIdRoute
  '/familles/': typeof FamillesIndexRoute
  '/transmissions/': typeof TransmissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activites'
    | '/audit'
    | '/connexion'
    | '/documents'
    | '/enfants'
    | '/facturation'
    | '/familles'
    | '/forbidden'
    | '/inscription'
    | '/inscriptions'
    | '/paiements'
    | '/parametres'
    | '/personnel'
    | '/planning'
    | '/presences'
    | '/rapports'
    | '/repas-hygiene'
    | '/sauvegarde'
    | '/transmissions'
    | '/utilisateurs'
    | '/enfants/$id'
    | '/familles/$id'
    | '/personnel/$employeeId'
    | '/transmissions/$childId'
    | '/familles/'
    | '/transmissions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activites'
    | '/audit'
    | '/connexion'
    | '/documents'
    | '/enfants'
    | '/facturation'
    | '/forbidden'
    | '/inscription'
    | '/inscriptions'
    | '/paiements'
    | '/parametres'
    | '/personnel'
    | '/planning'
    | '/presences'
    | '/rapports'
    | '/repas-hygiene'
    | '/sauvegarde'
    | '/utilisateurs'
    | '/enfants/$id'
    | '/familles/$id'
    | '/personnel/$employeeId'
    | '/transmissions/$childId'
    | '/familles'
    | '/transmissions'
  id:
    | '__root__'
    | '/'
    | '/activites'
    | '/audit'
    | '/connexion'
    | '/documents'
    | '/enfants'
    | '/facturation'
    | '/familles'
    | '/forbidden'
    | '/inscription'
    | '/inscriptions'
    | '/paiements'
    | '/parametres'
    | '/personnel'
    | '/planning'
    | '/presences'
    | '/rapports'
    | '/repas-hygiene'
    | '/sauvegarde'
    | '/transmissions'
    | '/utilisateurs'
    | '/enfants/$id'
    | '/familles/$id'
    | '/personnel/$employeeId'
    | '/transmissions/$childId'
    | '/familles/'
    | '/transmissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitesRoute: typeof ActivitesRoute
  AuditRoute: typeof AuditRoute
  ConnexionRoute: typeof ConnexionRoute
  DocumentsRoute: typeof DocumentsRoute
  EnfantsRoute: typeof EnfantsRouteWithChildren
  FacturationRoute: typeof FacturationRoute
  FamillesRoute: typeof FamillesRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  InscriptionRoute: typeof InscriptionRoute
  InscriptionsRoute: typeof InscriptionsRoute
  PaiementsRoute: typeof PaiementsRoute
  ParametresRoute: typeof ParametresRoute
  PersonnelRoute: typeof PersonnelRouteWithChildren
  PlanningRoute: typeof PlanningRoute
  PresencesRoute: typeof PresencesRoute
  RapportsRoute: typeof RapportsRoute
  RepasHygieneRoute: typeof RepasHygieneRoute
  SauvegardeRoute: typeof SauvegardeRoute
  TransmissionsRoute: typeof TransmissionsRouteWithChildren
  UtilisateursRoute: typeof UtilisateursRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activites': {
      id: '/activites'
      path: '/activites'
      fullPath: '/activites'
      preLoaderRoute: typeof ActivitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enfants': {
      id: '/enfants'
      path: '/enfants'
      fullPath: '/enfants'
      preLoaderRoute: typeof EnfantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturation': {
      id: '/facturation'
      path: '/facturation'
      fullPath: '/facturation'
      preLoaderRoute: typeof FacturationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familles': {
      id: '/familles'
      path: '/familles'
      fullPath: '/familles'
      preLoaderRoute: typeof FamillesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscriptions': {
      id: '/inscriptions'
      path: '/inscriptions'
      fullPath: '/inscriptions'
      preLoaderRoute: typeof InscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiements': {
      id: '/paiements'
      path: '/paiements'
      fullPath: '/paiements'
      preLoaderRoute: typeof PaiementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personnel': {
      id: '/personnel'
      path: '/personnel'
      fullPath: '/personnel'
      preLoaderRoute: typeof PersonnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presences': {
      id: '/presences'
      path: '/presences'
      fullPath: '/presences'
      preLoaderRoute: typeof PresencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapports': {
      id: '/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof RapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repas-hygiene': {
      id: '/repas-hygiene'
      path: '/repas-hygiene'
      fullPath: '/repas-hygiene'
      preLoaderRoute: typeof RepasHygieneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sauvegarde': {
      id: '/sauvegarde'
      path: '/sauvegarde'
      fullPath: '/sauvegarde'
      preLoaderRoute: typeof SauvegardeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transmissions': {
      id: '/transmissions'
      path: '/transmissions'
      fullPath: '/transmissions'
      preLoaderRoute: typeof TransmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilisateurs': {
      id: '/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof UtilisateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enfants/$id': {
      id: '/enfants/$id'
      path: '/$id'
      fullPath: '/enfants/$id'
      preLoaderRoute: typeof EnfantsIdRouteImport
      parentRoute: typeof EnfantsRoute
    }
    '/familles/': {
      id: '/familles/'
      path: '/'
      fullPath: '/familles/'
      preLoaderRoute: typeof FamillesIndexRouteImport
      parentRoute: typeof FamillesRoute
    }
    '/familles/$id': {
      id: '/familles/$id'
      path: '/$id'
      fullPath: '/familles/$id'
      preLoaderRoute: typeof FamillesIdRouteImport
      parentRoute: typeof FamillesRoute
    }
    '/personnel/$employeeId': {
      id: '/personnel/$employeeId'
      path: '/$employeeId'
      fullPath: '/personnel/$employeeId'
      preLoaderRoute: typeof PersonnelEmployeeIdRouteImport
      parentRoute: typeof PersonnelRoute
    }
    '/transmissions/': {
      id: '/transmissions/'
      path: '/'
      fullPath: '/transmissions/'
      preLoaderRoute: typeof TransmissionsIndexRouteImport
      parentRoute: typeof TransmissionsRoute
    }
    '/transmissions/$childId': {
      id: '/transmissions/$childId'
      path: '/$childId'
      fullPath: '/transmissions/$childId'
      preLoaderRoute: typeof TransmissionsChildIdRouteImport
      parentRoute: typeof TransmissionsRoute
    }
  }
}

interface EnfantsRouteChildren {
  EnfantsIdRoute: typeof EnfantsIdRoute
}

const EnfantsRouteChildren: EnfantsRouteChildren = {
  EnfantsIdRoute: EnfantsIdRoute,
}

const EnfantsRouteWithChildren =
  EnfantsRoute._addFileChildren(EnfantsRouteChildren)

interface FamillesRouteChildren {
  FamillesIdRoute: typeof FamillesIdRoute
  FamillesIndexRoute: typeof FamillesIndexRoute
}

const FamillesRouteChildren: FamillesRouteChildren = {
  FamillesIdRoute: FamillesIdRoute,
  FamillesIndexRoute: FamillesIndexRoute,
}

const FamillesRouteWithChildren = FamillesRoute._addFileChildren(
  FamillesRouteChildren,
)

interface PersonnelRouteChildren {
  PersonnelEmployeeIdRoute: typeof PersonnelEmployeeIdRoute
}

const PersonnelRouteChildren: PersonnelRouteChildren = {
  PersonnelEmployeeIdRoute: PersonnelEmployeeIdRoute,
}

const PersonnelRouteWithChildren = PersonnelRoute._addFileChildren(
  PersonnelRouteChildren,
)

interface TransmissionsRouteChildren {
  TransmissionsChildIdRoute: typeof TransmissionsChildIdRoute
  TransmissionsIndexRoute: typeof TransmissionsIndexRoute
}

const TransmissionsRouteChildren: TransmissionsRouteChildren = {
  TransmissionsChildIdRoute: TransmissionsChildIdRoute,
  TransmissionsIndexRoute: TransmissionsIndexRoute,
}

const TransmissionsRouteWithChildren = TransmissionsRoute._addFileChildren(
  TransmissionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitesRoute: ActivitesRoute,
  AuditRoute: AuditRoute,
  ConnexionRoute: ConnexionRoute,
  DocumentsRoute: DocumentsRoute,
  EnfantsRoute: EnfantsRouteWithChildren,
  FacturationRoute: FacturationRoute,
  FamillesRoute: FamillesRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  InscriptionRoute: InscriptionRoute,
  InscriptionsRoute: InscriptionsRoute,
  PaiementsRoute: PaiementsRoute,
  ParametresRoute: ParametresRoute,
  PersonnelRoute: PersonnelRouteWithChildren,
  PlanningRoute: PlanningRoute,
  PresencesRoute: PresencesRoute,
  RapportsRoute: RapportsRoute,
  RepasHygieneRoute: RepasHygieneRoute,
  SauvegardeRoute: SauvegardeRoute,
  TransmissionsRoute: TransmissionsRouteWithChildren,
  UtilisateursRoute: UtilisateursRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
